server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
          filters:
#            - My1=atguigu
#            - After=2024-04-02T00:00:00.000+08:00[Asia/Shanghai]
#            - Before=2024-04-02T00:00:00.000+08:00[Asia/Shanghai]
#            - Between=2024-04-02T00:00:00.000+08:00[Asia/Shanghai],2024-04-03T00:00:00.000+08:00[Asia/Shanghai]
#            - Cookie=username,qrh
#            - Header=X-Request-Id,123456
#            - Host=**.atguigu.com
#            - Method=GET,POST #注意需要大写，小写不行
#            - RemoteAddr=192.168.10.1/24
#            - My=diamod #自定义的断言参数

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
#          filters:
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
##            - RemoveRequestHeader=X-Request-atguigu1
#            - SetRequestHeader=X-Request-atguigu2,HelloWorld
#            - SetRequestHeader=X-request-atguigu3,guiguValue3
#            - AddRequestParameter=customerId,1234566
#            - RemoveRequestParameter=customerName

